Default Template updated, Parameter protection added
boundary/meter-plugin-remedy pull request #27
Opened 2017-10-31 08:27 UTC by vitiwari

@gokumar 
1) Incident Default Template updated.
2)Parameter Protection implemented.

2017-11-14 04:44 UTC, Kumar-Patil approved these changes
Looks good +

2017-11-27 05:16 UTC, gokumar requested changes

2017-11-27 05:16 UTC, gokumar commented on README.md
> +|Remedy Invalid Events Count              | Remedy Invalid events with size greater than limit     |
In "Description", do we need to mention the default limit?

2017-11-27 05:16 UTC, gokumar commented on README.md
> +Use [Config Generator] (https://github.com/boundary/remedy-tsi-bulkingestion-script/tree/master/dist/configgenerator) for generating Json template.
I can't find this URL.... maybe, not merged to "boundary" org yet?

2017-11-27 05:16 UTC, gokumar commented on metrics.json
> +  "REMEDY_INGESTION_INVALID_COUNT": {
Should we rather call it `REMEDY_INVALID_EVENTS_COUNT"`

2017-11-27 05:16 UTC, gokumar commented on metrics.json
> +  "REMEDY_INGESTION_INVALID_COUNT": {
Currently, it sounds like "invalid ingestion" which, is not the case...

2017-11-27 05:16 UTC, gokumar commented on src/main/java/com/bmc/truesight/meter/plugin/remedy/RemedyTicketsCollector.java
> +                        int recordsCount = remedyResponse.getValidEventList().size() + remedyResponse.getInvalidEventList().size();
Possible, NPEs here...?

2017-11-27 05:48 UTC, vitiwari commented on src/main/java/com/bmc/truesight/meter/plugin/remedy/RemedyTicketsCollector.java
> +                        int recordsCount = remedyResponse.getValidEventList().size() + remedyResponse.getInvalidEventList().size();
the library returns a list with either size 0 or more so NPEs aren't possible here.

2017-11-27 05:48 UTC, vitiwari commented on metrics.json
> +  "REMEDY_INGESTION_INVALID_COUNT": {
Agreed, I will change it.

2017-11-27 06:11 UTC, vitiwari commented on README.md
> +Use [Config Generator] (https://github.com/boundary/remedy-tsi-bulkingestion-script/tree/master/dist/configgenerator) for generating Json template.
correct. This is a cross link to the bulk-ingestion-script directory. It would be available once bulk ingestion is released(merged to boundary).

2017-11-27 06:12 UTC, gokumar approved these changes

2017-11-27 06:12 UTC, gokumar commented on metrics.json
> +    "description": "Remedy Invalid events with greater than size limit(32000 bytes)",
Need a `blank space` before `(`

2017-11-27 06:13 UTC, gokumar approved these changes

2017-11-27 06:13 UTC, gokumar commented on README.md
> +Use [Config Generator] (https://github.com/boundary/remedy-tsi-bulkingestion-script/tree/master/dist/configgenerator) for generating Json template.
Get this merged before you merge these changes...

2017-11-27 08:05 UTC, merged